### ISSUE TITLE
search is not working

### ISSUE THREAD

**Issue by Schlaefer** [infostreams/pagelist-snippet#1]
Using `(pagelist: search)` and `?q=foo` the `$content = $p->getContent();` [here](https://github.com/infostreams/pagelist-snippet/blob/1.0.1/Classes/Search.php#L14) results in an endless recursion of Phile's `before_parse_content` event?

**Comment by infostreams** [comment]
You were right. I think I fixed it - can you let me know if this works for  you?

**Comment by Schlaefer** [comment]
Works! :+1: :smiley:

**Comment by infostreams** [comment]
Great! :-)
