### ISSUE TITLE
Search does not work together with phileTags

### ISSUE THREAD

**Issue by pesasa** [infostreams/pagelist-snippet#2]
Search function of pagelist-snippets does not work, if [phileTags](https://github.com/pschmitt/phileTags) is installed.

In `Search.php`, on line 23 it tries to implode the array of all meta values. However, phileTags adds `tags_array` to the meta. And since that is an Array, not a String, the implode fails with en error.

The fix would be to select only String meta values and implode only those.

**Comment by infostreams** [comment]
Hey! Thanks for the bug report and the pull request! :-) I've taken a slightly different path and addressed this issue in this commit: e73a9b8b7837364b3fa2aa8b5e3881888c33571a

If you installed with composer you should be able to just update and get the new version (1.0.3). Can you let me know if it works? Thanks!

**Comment by pesasa** [comment]
Yes, that seems to work fine and is probably more elegant. Thanks.
