### ISSUE TITLE
Class 'Phile\Bootstrap' not found

### ISSUE THREAD

**Issue by rakeen** [infostreams/pagelist-snippet#5]
I'm using Phile v1.2.0

When I try to access the page it shows me **Fatal error: Class 'Phile\Bootstrap' not found in \Phile\plugins\infostreams\pagelistSnippet\Classes\Plugin.php on line 52**

**Comment by infostreams** [comment]
If I remember correctly I started writing this plugin when Phile was at v1.3.0. I'm not sure if I want to backport it to work with older versions.

What the code on line 52 does is try to register the Pagelist plugin with the [Snippets](https://github.com/infostreams/snippets) class. It does that by looking up which plugins are registered, and it needs the Phile\Bootstrap class to achieve that. However, it seems that this class is not yet present in v1.2.0. If you manage to find a way to make it work, please submit a pull request. Alternatively, you could consider upgrading your PhileCMS version to ≥ 1.3.0

Upgrading PhileCMS to 1.3.0 should not be too difficult, and it hopefully wouldn't break your site. Let me know if it works out.
