### ISSUE TITLE
Conflict with the TableOfContents plugin

### ISSUE THREAD

**Issue by nlile** [infostreams/pagelist-snippet#7]
Independently, both plugins work perfectly. [Table of Contents plugin](https://github.com/pschmitt/phileTableOfContents) and [Pagelist search](https://github.com/infostreams/pagelist-snippet). However, when they are both active, using the (pagelist: search) throws an error. 

> Call to undefined method Phile\Plugin\Infostreams\PagelistSnippet\DummyMeta::getAll() [1] 
> triggered in file ...\plugins\gibbs\phileTableOfContents\Classes\Plugin.php on line 39 .

The Table of Contents code that pagelist is conflicting with:

```
00034:         { 
00035:             $toc = array(); 
00036:             $tags = $this->settings['tags']; 
00037:  
00038:             $page = $data['data']['current_page']; 
00039:             $meta = $page->getMeta()->getAll(); 
00040:  
00041:             // Determine if we should return a TOC or not 
00042:             $tag = $this->settings['metatag']; 
00043:  
00044:             $metatag = isset($meta[$tag]) ? $meta[$tag] : null; 
```

Any ideas on the issue? I'm not familiar enough with the inter-workings of Phile. Thanks @infostreams

**Comment by infostreams** [comment]
Hi @nlile! Thanks for using this plugin. I tried to reproduce your problem but I ran into trouble the moment I enabled the Table of Contents plugin, even without the (pagelist: search) tag anywhere.

However, I have a hunch that might be able to solve your problem. Can you open `plugins\infostreams\pagelistSnippet\Classes\PagelistSnippet.php`, scroll to the end of the file and add a dummy `getAll()` method, so that the resulting class ("DummyMeta") looks like this?

```php
class DummyMeta {
	protected $template;

	public function __construct($template) {
		$this->template = $template;
	}

	public function get($k) {
		return $this->template;
	}

	public function getAll() {
		return array();
	}
}
```

Does that resolve your error? If so, please submit a pull request with the above and you'll be named as a contributor to the plugin ;-)

**Comment by nlile** [comment]
@infostreams for some reason I never saw the notification that you responded!

I added a dummy getAll() and the result was a new error from the TOC plugin haha. 

_DOMDocument::loadHTML(): Empty string supplied as input [2]
\phileTableOfContents\Classes\Plugin.php on line 60_

> // If for whatever reason the HTML fails to load just give up 
> try { 
> $doc->loadHTML($data['data']['content']); 
> } 
> catch(\Exception $e) { 
> return; 
> }

@infostreams  and then there's a 25 step backtrace.

**Comment by nlile** [comment]
Sort of a cheap solution, but no errors are thrown when I add this check:
```
            // If for whatever reason the HTML fails to load just give up
            try {
                if(!empty($data['data']['content'])){
                $doc->loadHTML($data['data']['content']);}
            }
```

**Comment by infostreams** [comment]
Ok, well if it works it works. This is more an issue with the other plugin to be honest. You want to make a pull request for the 'getAll' method so that you are in the list of contributors? If not I can do it. 

Cheers,
Ed

**Comment by nlile** [comment]
Awesome, thank you! Sent the request.
