### ISSUE TITLE
Fatal error: Class 'Phile\Plugin\Infostreams\Snippets\Snippets' not found in 

### ISSUE THREAD

**Issue by ghost** [infostreams/pagelist-snippet#9]
Hello Developers,

I have already installed several Phile plugins today and would like to create a "search.md" page. I placed this content in the content of the .md-page.

    (pagelist: all)

If I then want to call the frontend again, this error is displayed to me.

    Fatal error: Class 'Phile\Plugin\Infostreams\Snippets\Snippets' not found in /xxxxxxxxxxxxxxxxxxxx/phile.wpzweinull.ch/plugins/infostreams/pagelistSnippet/Classes/PagelistSnippet.php on line 4

I downloaded the last branch from this repo.

Can you see this please.

Thanks in advance.

**Comment by infostreams** [comment]
Hi Alexander,

How do I reproduce this bug? How did you install the plugin, on which version of phile, and can you show me the configuration? Thanks!

Ed

**Comment by ghost** [comment]
Hi,

Thank you for registering here. So I put on the last phile version of github. To reproduce the bug, you have to upload the last plugin version to `/infostreams/pagelistSnippets`.

Then I added in the file config.php in the root directory. It looks altogether like this.

```
<?php

/**
 * Set configuration of your phile installation.
 *
 * You can also overwrite Phile-defaults here.
 */
$config = [];

/**
 * encryption key
 */
$config['encryptionKey'] = 'ZlTcBtDF7Z0Xkxx6exIV0BIO[!GIcbq3vXL4R[/QtMXnjJ0FK!m(YRKGyiJL5c1c';

/**
 * page title
 */
$config['site_title'] = 'PhileCMS - CMS - Blog';

/**
 * default theme
 */
$config['theme'] = 'blog';

/**
 * demo plugin
 */
// $config['plugins']['mycompany\\demoPlugin'] = ['active' => true];
$config['plugins']['phile\\rssFeed'] = array('active' => true);
$config['plugins']['phile\\inlineImage'] = array('active' => true);
$config['plugins']['phile\\xmlsitemap'] = array('active' => true);
$config['plugins']['siezi\\phileAdmin'] = ['active' => false];
// $config['plugins']['stijnFlipper\\philePaginator'] = array('active' => true);
// $config['plugins']['phileCustomizeLinks'] = array('active' => true);
$config['plugins']['siezi\\phileSyntaxHighlight'] = ['active' => true];
$config['plugins']['phile\\markdownExtraExtended'] = array('active' => true);

$config['plugins'] = array(
    // [...]
    'pschmitt\\tags' => array('active' => true),
);

$config['plugins'] = array(
    // [...]
    'pschmitt\\tableOfContents' => array('active' => true),
);

$config['plugins']['infostreams\\pagelistSnippet'] = array('active' => true);


return $config;
```

The plugin config.php looks like this. I use the last branch of the plugins here from you.

```
<?php
/**
 * config file
 */
return array(
        // Setting config information for PhileAdmin
        'info' => array(
                'author' => array(
                        'name'     => 'Edward Akerboom',
                        'homepage' => 'https://github.com/infostreams'
                ),
                'namespace' => 'Infostreams',
                'url'       => 'https://github.com/infostreams/pagelistSnippet',
        ),
);
```

Maybe you know more now.

Thanks in advance.

**Comment by ghost** [comment]
Sorry, this plugin at https://github.com/infostreams/snippets was not installed yet.

Since I would just like to deal with the Phile CMS, I could not yet guess.

The result of the search page I have already at https://phile.wpzweinull.ch/suche. It now seems to work.
